-- ============================================================
--  SIANNA TRAVEL — Esquema Postgres (Easypanel)
--  Migración desde Supabase (proyecto cvtearllxmrdzuatipmo) + tablas del bot.
--
--  CÓMO USAR (DBGate, conectado al servicio sianna-sbd):
--    La base "sianna" ya existe. Solo:
--    1) Selecciona/conéctate a la base "sianna".
--    2) Ejecuta este archivo (01_schema.sql).
--    3) Luego: 02_usuarios.sql, 03_datos.sql, 04_bot_seed.sql.
-- ============================================================

-- ---------- Función para auto-actualizar updated_at ----------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================
--  PAQUETES  (migrada de Supabase)
-- ============================================================
CREATE TABLE IF NOT EXISTS packages (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug                TEXT UNIQUE,
  title               TEXT NOT NULL,
  destination         TEXT,
  country             TEXT,
  region              TEXT,
  description         TEXT,
  price               INTEGER      DEFAULT 0,
  original_price      INTEGER      DEFAULT 0,
  discount            INTEGER      DEFAULT 0,
  currency            TEXT         DEFAULT 'MXN',
  duration            TEXT,
  nights              INTEGER      DEFAULT 0,
  image               TEXT,
  gallery             JSONB        DEFAULT '[]'::jsonb,
  category            TEXT         DEFAULT 'aventura',
  rating              NUMERIC(2,1) DEFAULT 4.5,
  reviews_count       INTEGER      DEFAULT 0,
  includes            JSONB        DEFAULT '[]'::jsonb,
  highlights          JSONB        DEFAULT '[]'::jsonb,
  is_active           BOOLEAN      DEFAULT true,
  is_featured         BOOLEAN      DEFAULT false,
  order_index         INTEGER      DEFAULT 0,
  airline             TEXT,
  flight_type         TEXT         DEFAULT 'internacional',
  service_type        TEXT         DEFAULT 'paquete',
  persons             INTEGER      DEFAULT 2,
  hotel_name          TEXT,
  hotel_stars         INTEGER,
  room_type           TEXT,
  accommodation_type  TEXT,
  itinerary_pdf       TEXT,
  dates               TEXT,
  contact_whatsapp    TEXT,
  cancellation_policy TEXT,
  flight_includes     JSONB        DEFAULT '[]'::jsonb,
  transfers_included  JSONB        DEFAULT '[]'::jsonb,
  itinerary           JSONB        DEFAULT '[]'::jsonb,
  important_info      JSONB        DEFAULT '[]'::jsonb,
  terms_conditions    JSONB        DEFAULT '[]'::jsonb,
  payment_options     JSONB        DEFAULT '[]'::jsonb,
  created_at          TIMESTAMPTZ  DEFAULT now(),
  updated_at          TIMESTAMPTZ  DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_packages_active   ON packages (is_active);
CREATE INDEX IF NOT EXISTS idx_packages_featured ON packages (is_featured);
CREATE INDEX IF NOT EXISTS idx_packages_order    ON packages (order_index);
DROP TRIGGER IF EXISTS trg_packages_updated ON packages;
CREATE TRIGGER trg_packages_updated BEFORE UPDATE ON packages
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
--  HISTORIAL DE CAMBIOS DE PAQUETES  (migrada de Supabase)
-- ============================================================
CREATE TABLE IF NOT EXISTS package_history (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  package_id    BIGINT REFERENCES packages(id) ON DELETE CASCADE,
  field_changed TEXT,
  old_value     TEXT,
  new_value     TEXT,
  changed_by    TEXT,
  changed_at    TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_history_package ON package_history (package_id);

-- ============================================================
--  PROMOCIONES DESTACADAS  (migrada de Supabase)
-- ============================================================
CREATE TABLE IF NOT EXISTS featured_packages (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title          TEXT,
  destination    TEXT,
  price          INTEGER DEFAULT 0,
  original_price INTEGER DEFAULT 0,
  discount       INTEGER DEFAULT 0,
  image          TEXT,
  tag            TEXT,
  nights         INTEGER DEFAULT 0,
  rating         NUMERIC(2,1) DEFAULT 4.5,
  link           TEXT,
  order_index    INTEGER DEFAULT 0,
  itinerary_pdf  TEXT,
  created_at     TIMESTAMPTZ DEFAULT now(),
  updated_at     TIMESTAMPTZ DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_featured_updated ON featured_packages;
CREATE TRIGGER trg_featured_updated BEFORE UPDATE ON featured_packages
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
--  BLOG  (migrada de Supabase)
--  content = JSON serializado en texto (bloques type/value), igual que hoy.
-- ============================================================
CREATE TABLE IF NOT EXISTS blog_posts (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title        TEXT,
  slug         TEXT UNIQUE,
  excerpt      TEXT,
  cover_image  TEXT,
  content      TEXT,
  author       TEXT,
  is_published BOOLEAN DEFAULT false,
  published_at TIMESTAMPTZ,
  created_at   TIMESTAMPTZ DEFAULT now(),
  updated_at   TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_blog_published ON blog_posts (is_published);
DROP TRIGGER IF EXISTS trg_blog_updated ON blog_posts;
CREATE TRIGGER trg_blog_updated BEFORE UPDATE ON blog_posts
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
--  FAQ DEL BOT  (NUEVA — reemplaza la hoja "FAQs" de Google Sheets)
-- ============================================================
CREATE TABLE IF NOT EXISTS faq (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria  TEXT,                     -- tema/área (ej. "Pagos", "Reservas")
  pregunta   TEXT NOT NULL,
  respuesta  TEXT NOT NULL,
  activo     BOOLEAN DEFAULT true,
  orden      INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_faq_activo ON faq (activo);
DROP TRIGGER IF EXISTS trg_faq_updated ON faq;
CREATE TRIGGER trg_faq_updated BEFORE UPDATE ON faq
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
--  SOLICITUDES DE MENSAJE / LEADS  (NUEVA)
--  Reemplaza las hojas "Tickets" + handoff. 1 fila por número (estado del contacto).
-- ============================================================
CREATE TABLE IF NOT EXISTS solicitudes (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_whatsapp    TEXT UNIQUE,           -- clave de match (igual que el bot)
  nombre_cliente     TEXT,
  correo             TEXT,
  origen             TEXT    DEFAULT 'WhatsApp',
  numero_negocio     TEXT,
  tipo_servicio      TEXT,
  descripcion        TEXT,
  estado             TEXT    DEFAULT 'Nuevo',     -- Nuevo / Escalado / Atendido / Cerrado
  prioridad          TEXT    DEFAULT 'MEDIA',     -- BAJA / MEDIA / ALTA
  asesor             TEXT,                        -- Bianka / Gaby
  ultimo_mensaje     TEXT,
  seguimiento_enviado BOOLEAN DEFAULT false,
  bot_pausado        BOOLEAN DEFAULT false,       -- handoff: el bot se calla
  fecha_pausa_bot    TIMESTAMPTZ,
  intencion_compra   BOOLEAN DEFAULT false,
  fecha_hora         TIMESTAMPTZ DEFAULT now(),
  created_at         TIMESTAMPTZ DEFAULT now(),
  updated_at         TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_solicitudes_estado    ON solicitudes (estado);
CREATE INDEX IF NOT EXISTS idx_solicitudes_prioridad ON solicitudes (prioridad);
DROP TRIGGER IF EXISTS trg_solicitudes_updated ON solicitudes;
CREATE TRIGGER trg_solicitudes_updated BEFORE UPDATE ON solicitudes
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
--  LINKS / ENLACES EDITABLES  (NUEVA)
--  Enlaces que el bot puede enviar (catálogo, web, redes, PDFs...).
-- ============================================================
CREATE TABLE IF NOT EXISTS links (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  clave       TEXT UNIQUE NOT NULL,   -- ej. 'catalogo', 'web', 'instagram'
  titulo      TEXT,
  url         TEXT NOT NULL,
  descripcion TEXT,
  activo      BOOLEAN DEFAULT true,
  orden       INTEGER DEFAULT 0,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now()
);
DROP TRIGGER IF EXISTS trg_links_updated ON links;
CREATE TRIGGER trg_links_updated BEFORE UPDATE ON links
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
