-- ============================================================
--  SIANNA TRAVEL — Login propio del admin (Easypanel)
--  Ejecutar como "postgres" conectado a la base "sianna".
--  El backend (sianna_app) consulta esta tabla para el login.
-- ============================================================

CREATE TABLE IF NOT EXISTS admin_users (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email         TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  nombre        TEXT,
  activo        BOOLEAN DEFAULT true,
  created_at    TIMESTAMPTZ DEFAULT now()
);

-- El backend necesita LEER esta tabla (login). NO le damos escritura.
GRANT SELECT ON admin_users TO sianna_app;

-- ---------- Usuario admin inicial ----------
-- Email:      admin@siannatravel.com
-- Contraseña: SiannaAdmin2026   (CÁMBIALA tras el primer acceso)
-- El hash es bcrypt; para regenerarlo:  node src/scripts/hash.js "nueva-clave"
INSERT INTO admin_users (email, password_hash, nombre)
VALUES (
  'admin@siannatravel.com',
  '$2a$10$3Q1Hif7P9MJK0VYF8nZ6he0RXcry7XRBZsbpVRFD0A./FOeFgqDDG',
  'Administrador Sianna'
)
ON CONFLICT (email) DO NOTHING;
